#ifndef __ERROR_H
#define __ERROR_H

#include <stdio.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
    ODAS2_ERROR_NONE,

    ODAS2_ERROR_MSGOUT_CONSTRUCT_FILE_CREATION,
    ODAS2_ERROR_MSGOUT_WRITE,

    ODAS2_ERROR_RAWOUT_CONSTRUCT_FILE_CREATION,
    ODAS2_ERROR_RAWOUT_WRITE,

    ODAS2_ERROR_WAVIN_CONSTRUCT_FILE_NOT_EXIST,
    ODAS2_ERROR_WAVIN_CONSTRUCT_INVALID_WAV_FILE,
    ODAS2_ERROR_WAVIN_CONSTRUCT_INVALID_WAV_HEADER,

    ODAS2_ERROR_WAVOUT_CONSTRUCT_FILE_CREATION,
    ODAS2_ERROR_WAVOUT_CONSTRUCT_HEADER_WRITE,
    ODAS2_ERROR_WAVOUT_WRITE_SAMPLES,

    ODAS2_ERROR_COVS_CONSTRUCT_LABEL,
    ODAS2_ERROR_COVS_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_COVS_CONSTRUCT_NUM_BINS,

    ODAS2_ERROR_DOAS_CONSTRUCT_LABEL,
    ODAS2_ERROR_DOAS_CONSTRUCT_NUM_DIRECTIONS,

    ODAS2_ERROR_DSF_CONSTRUCT_LABEL,

    ODAS2_ERROR_FREQS_CONSTRUCT_LABEL,
    ODAS2_ERROR_FREQS_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_FREQS_CONSTRUCT_NUM_BINS,

    ODAS2_ERROR_HOPS_CONSTRUCT_LABEL,
    ODAS2_ERROR_HOPS_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_HOPS_CONSTRUCT_NUM_SHIFTS,

    ODAS2_ERROR_MASKS_CONSTRUCT_LABEL,
    ODAS2_ERROR_MASKS_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_MASKS_CONSTRUCT_NUM_BINS,

    ODAS2_ERROR_TDOAS_CONSTRUCT_LABEL,
    ODAS2_ERROR_TDOAS_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_TDOAS_CONSTRUCT_NUM_SOURCES,

    ODAS2_ERROR_WEIGHTS_CONSTRUCT_LABEL,
    ODAS2_ERROR_WEIGHTS_CONSTRUCT_NUM_SOURCES,
    ODAS2_ERROR_WEIGHTS_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_WEIGHTS_CONSTRUCT_NUM_BINS,

    ODAS2_ERROR_FFT_CONSTRUCT_INVALID_NUM_SAMPLES,

    ODAS2_ERROR_MICS_HARDWARE_UNKNOWN,

    ODAS2_ERROR_POINTS_GEOMETRY_UNKNOWN,

    ODAS2_ERROR_BEAMFORMER_CONSTRUCT_NUM_SOURCES,
    ODAS2_ERROR_BEAMFORMER_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_BEAMFORMER_CONSTRUCT_NUM_BINS,
    ODAS2_ERROR_BEAMFORMER_PROCESS_WEIGHTS_NUM_SOURCES,
    ODAS2_ERROR_BEAMFORMER_PROCESS_WEIGHTS_NUM_CHANNELS,
    ODAS2_ERROR_BEAMFORMER_PROCESS_WEIGHTS_NUM_BINS,
    ODAS2_ERROR_BEAMFORMER_PROCESS_IN_NUM_CHANNELS,
    ODAS2_ERROR_BEAMFORMER_PROCESS_IN_NUM_BINS,
    ODAS2_ERROR_BEAMFORMER_PROCESS_OUT_NUM_CHANNELS,
    ODAS2_ERROR_BEAMFORMER_PROCESS_OUT_NUM_BINS,

    ODAS2_ERROR_DELAYSUM_CONSTRUCT_NUM_SOURCES,
    ODAS2_ERROR_DELAYSUM_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_DELAYSUM_CONSTRUCT_NUM_BINS,
    ODAS2_ERROR_DELAYSUM_PROCESS_TDOAS_NUM_SOURCES,
    ODAS2_ERROR_DELAYSUM_PROCESS_TDOAS_NUM_CHANNELS,
    ODAS2_ERROR_DELAYSUM_PROCESS_WEIGHTS_NUM_SOURCES,
    ODAS2_ERROR_DELAYSUM_PROCESS_WEIGHTS_NUM_CHANNELS,
    ODAS2_ERROR_DELAYSUM_PROCESS_WEIGHTS_NUM_BINS,

    ODAS2_ERROR_ENHANCEMENT_INVALID_NUM_BINS,

    ODAS2_ERROR_GCC_CONSTRUCT_NUM_SOURCES,
    ODAS2_ERROR_GCC_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_GCC_CONSTRUCT_NUM_BINS,
    ODAS2_ERROR_GCC_PROCESS_TDOAS_NUM_SOURCES,
    ODAS2_ERROR_GCC_PROCESS_TDOAS_NUM_CHANNELS,
    ODAS2_ERROR_GCC_PROCESS_COVS_NUM_CHANNELS,
    ODAS2_ERROR_GCC_PROCESS_COVS_NUM_BINS,

    ODAS2_ERROR_MIXER_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_MIXER_PROCESS_MAX_MAP_INDEX,
    ODAS2_ERROR_MIXER_PROCESS_NUM_CHANNELS,

    ODAS2_ERROR_MVDR_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_MVDR_CONSTRUCT_NUM_BINS,
    ODAS2_ERROR_MVDR_PROCESS_COVS_NUM_CHANNELS,
    ODAS2_ERROR_MVDR_PROCESS_COVS_NUM_BINS,
    ODAS2_ERROR_MVDR_PROCESS_WEIGHTS_NUM_SOURCES,
    ODAS2_ERROR_MVDR_PROCESS_WEIGHTS_NUM_CHANNELS,
    ODAS2_ERROR_MVDR_PROCESS_WEIGHTS_NUM_BINS,

    ODAS2_ERROR_PHAT_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_PHAT_CONSTRUCT_NUM_BINS,
    ODAS2_ERROR_PHAT_PROCESS_COVS_IN_NUM_CHANNELS,
    ODAS2_ERROR_PHAT_PROCESS_COVS_IN_NUM_BINS,
    ODAS2_ERROR_PHAT_PROCESS_COVS_OUT_NUM_CHANNELS,
    ODAS2_ERROR_PHAT_PROCESS_COVS_OUT_NUM_BINS,

    ODAS2_ERROR_POSTFILTER_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_POSTFILTER_CONSTRUCT_NUM_BINS,
    ODAS2_ERROR_POSTFILTER_PROCESS_FREQS_IN_NUM_CHANNELS,
    ODAS2_ERROR_POSTFILTER_PROCESS_FREQS_IN_NUM_BINS,
    ODAS2_ERROR_POSTFILTER_PROCESS_MASKS_NUM_CHANNELS,
    ODAS2_ERROR_POSTFILTER_PROCESS_MASKS_NUM_BINS,
    ODAS2_ERROR_POSTFILTER_PROCESS_FREQS_OUT_NUM_CHANNELS,
    ODAS2_ERROR_POSTFILTER_PROCESS_FREQS_OUT_NUM_BINS,

    ODAS2_ERROR_SCM_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_SCM_CONSTRUCT_NUM_BINS,
    ODAS2_ERROR_SCM_CONSTRUCT_ALPHA,
    ODAS2_ERROR_SCM_PROCESS_FREQS_NUM_CHANNELS,
    ODAS2_ERROR_SCM_PROCESS_FREQS_NUM_BINS,
    ODAS2_ERROR_SCM_PROCESS_MASKS_NUM_CHANNELS,
    ODAS2_ERROR_SCM_PROCESS_MASKS_NUM_BINS,
    ODAS2_ERROR_SCM_PROCESS_COVS_NUM_CHANNELS,
    ODAS2_ERROR_SCM_PROCESS_COVS_NUM_BINS,

    ODAS2_ERROR_SSL_CONSTRUCT_NUM_MICS,
    ODAS2_ERROR_SSL_CONSTRUCT_NUM_POINTS,
    ODAS2_ERROR_SSL_CONSTRUCT_SAMPLE_RATE,
    ODAS2_ERROR_SSL_CONSTRUCT_SOUND_SPEED,
    ODAS2_ERROR_SSL_CONSTRUCT_NUM_SOURCES,
    ODAS2_ERROR_SSL_CONSTRUCT_NUM_DIRECTIONS,
    ODAS2_ERROR_SSL_PROCESS_TDOAS_NUM_SOURCES,
    ODAS2_ERROR_SSL_PROCESS_TDOAS_NUM_CHANNELS,
    ODAS2_ERROR_SSL_PROCESS_DOAS_NUM_DIRECTIONS,

    ODAS2_ERROR_SST_CONSTRUCT_NUM_TRACKS,
    ODAS2_ERROR_SST_CONSTRUCT_NUM_DIRECTIONS,
    ODAS2_ERROR_SST_CONSTRUCT_NUM_PASTS,
    ODAS2_ERROR_SST_PROCESS_NUM_DIRECTIONS,
    ODAS2_ERROR_SST_PROCESS_NUM_TRACKS,

    ODAS2_ERROR_STEERING_CONSTRUCT_NUM_MICS,
    ODAS2_ERROR_STEERING_CONSTRUCT_SAMPLE_RATE,
    ODAS2_ERROR_STEERING_CONSTRUCT_SOUND_SPEED,
    ODAS2_ERROR_STEERING_CONSTRUCT_NUM_SOURCES,
    ODAS2_ERROR_STEERING_PROCESS_DOAS_NUM_DIRECTIONS,
    ODAS2_ERROR_STEERING_PROCESS_TDOAS_NUM_SOURCES,
    ODAS2_ERROR_STEERING_PROCESS_TDOAS_NUM_CHANNELS,

    ODAS2_ERROR_STFT_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_STFT_CONSTRUCT_NUM_SAMPLES,
    ODAS2_ERROR_STFT_CONSTRUCT_NUM_SHIFTS,
    ODAS2_ERROR_STFT_CONSTRUCT_INVALID_WINDOW,
    ODAS2_ERROR_STFT_PROCESS_HOPS_NUM_CHANNELS,
    ODAS2_ERROR_STFT_PROCESS_HOPS_NUM_SHIFTS,
    ODAS2_ERROR_STFT_PROCESS_FREQS_NUM_CHANNELS,
    ODAS2_ERROR_STFT_PROCESS_FREQS_NUM_BINS,

    ODAS2_ERROR_ISTFT_CONSTRUCT_NUM_CHANNELS,
    ODAS2_ERROR_ISTFT_CONSTRUCT_NUM_SAMPLES,
    ODAS2_ERROR_ISTFT_CONSTRUCT_NUM_SHIFTS,
    ODAS2_ERROR_ISTFT_CONSTRUCT_INVALID_WINDOW,
    ODAS2_ERROR_ISTFT_PROCESS_HOPS_NUM_CHANNELS,
    ODAS2_ERROR_ISTFT_PROCESS_HOPS_NUM_SHIFTS,
    ODAS2_ERROR_ISTFT_PROCESS_FREQS_NUM_CHANNELS,
    ODAS2_ERROR_ISTFT_PROCESS_FREQS_NUM_BINS,

    ODAS2_ERROR_UNKNOWN

} odas2_error_t;

odas2_error_t odas2_error_number();
const char* odas2_error_message();
void odas2_set_error_number(odas2_error_t err);

#define ODAS2_CHECK_PTR(ptr)                                                                                           \
    do                                                                                                                 \
    {                                                                                                                  \
        if ((ptr) == NULL)                                                                                             \
        {                                                                                                              \
            fprintf(stderr, "Error in %s:%d - %s\n", __FILE__, __LINE__, odas2_error_message());                       \
            exit(EXIT_FAILURE);                                                                                        \
        }                                                                                                              \
    } while (0)

#define ODAS2_CHECK_CODE(code)                                                                                         \
    do                                                                                                                 \
    {                                                                                                                  \
        if ((code) != 0)                                                                                               \
        {                                                                                                              \
            fprintf(stderr, "Error in %s:%d - %s\n", __FILE__, __LINE__, odas2_error_message());                       \
            exit(EXIT_FAILURE);                                                                                        \
        }                                                                                                              \
    } while (0)

#ifdef __cplusplus
}
#endif

#endif // __ERROR_H
