on:
  pull_request:
    branches:
      - main

name: Pull Request Audit

jobs:
  build-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-2022]
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Create Build Directory
        working-directory: core
        run: cmake -E make_directory build

      - name: Configure CMake
        working-directory: core/build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: core/build
        run: cmake --build .

      - name: Tests
        working-directory: core/bin
        shell: bash
        run: ./tests
